### ISSUE TITLE
При переходе на /profile выкидывает ошибку

### ISSUE THREAD

**Issue by olegpolyakov** [momonomonoto/server#12]
```
TypeError: Cannot read property 'name' of null
    at modelUser.findById.then.user (D:\codedojo\code-review\nodejs-in-action\momonomonoto\server\controllers\operationController.js:29:59)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by olegpolyakov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Выполнить ДЗ №5](https://trello.com/c/npzJKEZL/6-%D0%B2%D1%8B%D0%BF%D0%BE%D0%BB%D0%BD%D0%B8%D1%82%D1%8C-%D0%B4%D0%B7-%E2%84%965)

**Comment by momonomonoto** [comment]
Вот это и имел ввиду! Не проходит регистрация в паспорте!

**Comment by momonomonoto** [comment]
Исправлено
